### PR TITLE
BXB-4263 Update jsoncpp upstream

### PR DESCRIPTION
**Pull request by MattMacGregor**
A change in jsoncpp's CMake file led to it naming the library targets based off of the PROJECT_NAME variable. So this was incorrectly adding the jsoncpp library target as "mediacore_lib" or something similar depending on the top level directory. Manually setting this to jsoncpp makes the library target created as expected. Additionally, a change led to BUILD_SHARED_LIBS needing to be turned on manually.

### CODE REVIEW

**Comment by artasano** [comment]
Resolve the conflicts.

**Comment by MattMacGregor** [comment]
@artasano These were the conflicts that we decided it was just easiest to manually resolve them during the merge. It doesn't let me save to "resolution to the conflicts", unless I go ahead and merge, so wanted the LGTM beforehand. Resolution is just disregarding the develop CMakeList.txt and replacing it with the one in the branch being merged.

**Comment by artasano** [comment]
I meant you can manually resolve it on your computer and push it.

**Comment by artasano** [comment]
Do you mean, it does not allow it?

**Review by artasano — APPROVED** [review]

**Pull request merged**
